#!/usr/bin/env python3

import os
import re
import sys


VARIABLE = re.compile(r"\$(?:\{([A-Za-z_][A-Za-z0-9_]*)\}|([A-Za-z_][A-Za-z0-9_]*))")


def replace_variable(match: re.Match[str]) -> str:
    name = match.group(1) or match.group(2)
    return os.environ.get(name, "")


sys.stdout.write(VARIABLE.sub(replace_variable, sys.stdin.read()))
